Add storage connector (https://github.com/snowlift/trino-storage) to Trino image
stackabletech/docker-images pull request #397
Opened 2023-06-28 11:25 UTC by soenkeliebau

This requires the storage connector to be uploaded at `https://repo.stackable.tech/repository/packages/trino-storage/trino-storage-${VERSION}.zip` for all supported Trino versions.

2023-06-28 12:01 UTC, sbernauer requested changes

2023-06-28 12:01 UTC, sbernauer commented on trino/Dockerfile
> +RUN curl https://repo.stackable.tech/repository/packages/trino-storage/trino-storage-${PRODUCT}.zip -o /tmp/trino-storage-${PRODUCT}.zip && \
We should remove the .zip afterwards

2023-06-28 12:01 UTC, sbernauer commented on trino/CHANGELOG.md
> +- Experimental: Add Snowlift Trino Storage Connector (https://github.com/snowlift/trino-storage) ([#397])
```suggestion
- Experimental: Add [Snowlift Trino Storage Connector](https://github.com/snowlift/trino-storage) ([#397])
```

2023-06-28 13:18 UTC, soenkeliebau commented on trino/Dockerfile
> +RUN curl https://repo.stackable.tech/repository/packages/trino-storage/trino-storage-${PRODUCT}.zip -o /tmp/trino-storage-${PRODUCT}.zip && \
done

2023-06-29 10:25 UTC, sbernauer submitted a review, later dismissed

2023-06-29 10:25 UTC, sbernauer commented on trino/CHANGELOG.md
> +- [EXPERIMENTAL] Add [Snowlift Trino Storage Connector](https://github.com/snowlift/trino-storage) ([#397])
```suggestion
- [EXPERIMENTAL] Add [Snowlift Trino Storage Connector](https://github.com/snowlift/trino-storage), but only for Trino version 414 ([#397])
```

2023-06-29 10:30 UTC, sbernauer approved these changes

2023-06-29 10:42 UTC, merged