Fix/arm preperations
stackabletech/docker-images pull request #527
Opened 2023-12-27 08:32 UTC by Maleware

# Description

This PR fixes some problems with the arm build of our products.

Notable mentions:

   - Stackable-Base image has an updated sha to the manifest list of ubi8-minimal
   -  STATSD_EXPORTER is now a binary in nexus rahter then being pulled from their image
   -  OPA binary now available in nexus with both architectures
   -  ubi8-rust-builder has now a dependency to the corresponding manifest list
   - Testing_Tools has now a dependency to the corresponding manifest list

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
- [ ] Changes are OpenShift compatible
- [ ] All added packages (via microdnf or otherwise) have a comment on why they are added
- [ ] Things not downloaded from Red Hat repositories should be mirrored in the Stackable repository and downloaded from there
- [ ] All packages should have (if available) signatures/hashes verified
- [ ] Does your change affect an SBOM? Make sure to update all SBOMs
```

2023-12-27 08:59 UTC, sbernauer requested changes

2023-12-27 08:59 UTC, sbernauer commented on CHANGELOG.md
> +## [23.11.0] - 2023-11-23
I have to admit this is a bit confusing to me. What do you think of removing it again?
Also we should add entries for this PR

2023-12-27 08:59 UTC, sbernauer commented on airflow/Dockerfile
> +# Choosing correct binary with respect to architecture
```suggestion
```

2023-12-27 08:59 UTC, sbernauer commented on airflow/Dockerfile
>  ARG STATSD_EXPORTER
Can this be removed?

2023-12-27 08:59 UTC, sbernauer commented on opa/Dockerfile
> +    && curl --fail -L https://repo.stackable.tech/repository/packages/opa/opa_linux_${ARCH}_static_${PRODUCT} \
```suggestion
    && curl --fail -L "https://repo.stackable.tech/repository/packages/opa/opa_linux_${ARCH}_static_${PRODUCT}" \
```

2023-12-27 08:59 UTC, sbernauer commented on airflow/Dockerfile
> +RUN ARCH=$(arch | sed 's/^aarch64$/arm64/' | sed 's/^x86_64$/amd64/') \
```suggestion
RUN ARCH="$(arch | sed 's/^aarch64$/arm64/' | sed 's/^x86_64$/amd64/')" \
```

2023-12-27 08:59 UTC, sbernauer commented on opa/Dockerfile
> +RUN ARCH=$(arch | sed 's/^aarch64$/arm64/' | sed 's/^x86_64$/amd64/') \
```suggestion
RUN ARCH="$(arch | sed 's/^aarch64$/arm64/' | sed 's/^x86_64$/amd64/')" \
```

2023-12-27 08:59 UTC, sbernauer commented on stackable-base/Dockerfile
> +FROM registry.access.redhat.com/ubi8@sha256:449da7f8f2ef6285a8445a1e31af57a97b9dae5dcf009b1629c59742c89c68c3
Is the switch from ubi-minimal to ubi intentional?

2023-12-27 08:59 UTC, sbernauer commented on superset/Dockerfile
>  ARG STATSD_EXPORTER
Can this be removed?

2023-12-27 08:59 UTC, sbernauer commented on superset/Dockerfile
> +RUN ARCH=$(arch | sed 's/^aarch64$/arm64/' | sed 's/^x86_64$/amd64/') \
```suggestion
RUN ARCH="$(arch | sed 's/^aarch64$/arm64/' | sed 's/^x86_64$/amd64/')" \
```

2023-12-27 08:59 UTC, sbernauer commented on superset/Dockerfile
> +    && pushd /stackable && curl --fail -L https://repo.stackable.tech/repository/packages/statsd_exporter/statsd_exporter-${STATSD_EXPORTER}.linux-${ARCH}.tar.gz | tar -xzC /stackable && ln -s statsd
```suggestion
    && pushd /stackable && curl --fail -L "https://repo.stackable.tech/repository/packages/statsd_exporter/statsd_exporter-${STATSD_EXPORTER}.linux-${ARCH}.tar.gz" | tar -xzC /stackable && ln -s statsd_exporter-${STATSD_EXPORTER}.linux-${ARCH}/statsd_exporter statsd_exporter && popd
```

2023-12-27 08:59 UTC, sbernauer commented on testing-tools/Dockerfile
> +FROM python:3.11-slim-bullseye@sha256:286f2f1d6f2f730a44108656afb04b131504b610a6cb2f3413918e98dabba67e
:thinking:

2023-12-27 08:59 UTC, sbernauer commented on ubi8-rust-builder/Dockerfile
> +FROM registry.access.redhat.com/ubi8@sha256:449da7f8f2ef6285a8445a1e31af57a97b9dae5dcf009b1629c59742c89c68c3
Is the switch from ubi-minimal to ubi intentional?

2023-12-27 08:59 UTC, sbernauer commented on airflow/constraints-2.7.2-python39.txt
> +gevent==22.10.2
Same as with greenlet here

2023-12-27 08:59 UTC, sbernauer commented on airflow/constraints-2.6.1-python39.txt
> +greenlet==3.0.2
I'm no Python guy but I assume we need to be careful here making a breaking change with a Airflow dependency.
https://github.com/python-greenlet/greenlet/blob/master/CHANGES.rst#300a1-2023-06-21 sounds like Python 2.12 addition and 2.7, 3.5 and 3.6 removal as well as C++ bump.

WDYT of pulling in `3.0.2` only for the experimental ARM builds to not disturb the "production" x84 image?

2023-12-27 09:09 UTC, maltesander commented on airflow/Dockerfile
> +RUN ARCH=$(arch | sed 's/^aarch64$/arm64/' | sed 's/^x86_64$/amd64/') \
```suggestion
# Choosing correct binary with respect to architecture
RUN ARCH=$(arch | sed 's/^aarch64$/arm64/' | sed 's/^x86_64$/amd64/') \
```

2023-12-27 09:09 UTC, maltesander commented on stackable-base/Dockerfile
> +FROM registry.access.redhat.com/ubi8@sha256:449da7f8f2ef6285a8445a1e31af57a97b9dae5dcf009b1629c59742c89c68c3
This is copy / paste / merge problem? Do not do this... We want to have the latest ubi images, should not affect arm.

2023-12-27 09:09 UTC, maltesander commented on superset/Dockerfile
> +
Not a fan of push and pop d. Can we just use "curl -o .." or workdir or at least use wrapping (" && \") for better readability?

2023-12-27 09:09 UTC, maltesander commented on testing-tools/Dockerfile
> +FROM python:3.11-slim-bullseye@sha256:286f2f1d6f2f730a44108656afb04b131504b610a6cb2f3413918e98dabba67e
Formatter / linter?

2023-12-27 09:20 UTC, Maleware commented on airflow/constraints-2.7.2-python39.txt
> +gevent==22.10.2
Because... although they claim it gevent 23.9.1 is not building together with greenlet 3.0.2 on arm64.

2023-12-27 09:23 UTC, sbernauer commented on stackable-base/Dockerfile
> +FROM registry.access.redhat.com/ubi8@sha256:449da7f8f2ef6285a8445a1e31af57a97b9dae5dcf009b1629c59742c89c68c3
Reverted back to ubi8-minimal

2023-12-27 12:25 UTC, lfrancke commented on airflow/constraints-2.7.2-python39.txt
> +gevent==22.10.2
Fwiw I'm with Sebastian and Malte. We need to be careful with changing dependency versions

2024-07-23 07:09 UTC, Maleware commented
outdated, closing it.

2024-07-23 07:09 UTC, closed without merging