Add release components (product images) to the feature DB
stackabletech/docker-images pull request #528
Opened 2024-01-08 16:13 UTC by razvan

# Description

This PR is part of https://github.com/stackabletech/feature-tracker/issues/52 and depends on https://github.com/stackabletech/feature-tracker/pull/53.

It adds a new script that updates the feature DB for a given release (version).

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
- [ ] Changes are OpenShift compatible
- [ ] All added packages (via microdnf or otherwise) have a comment on why they are added
- [ ] Things not downloaded from Red Hat repositories should be mirrored in the Stackable repository and downloaded from there
- [ ] All packages should have (if available) signatures/hashes verified
- [ ] Does your change affect an SBOM? Make sure to update all SBOMs
```

2024-01-08 17:21 UTC, dervoeti reviewed
LGTM, just fixed capitalization in my own comments :slightly_smiling_face:

2024-01-08 17:21 UTC, dervoeti commented on update_feature_tracker_db.sh
> +	# -c: execute the provided command and exit
```suggestion
	# -AtR "": In this case this basically means "just output the content of the selected column"
	# -c: Execute the provided command and exit
```

2024-01-08 17:21 UTC, dervoeti commented on update_feature_tracker_db.sh
> +	# create release version if it does not exist
```suggestion
	# Create release version if it does not exist
```

2024-01-09 13:37 UTC, lfrancke requested changes

2024-01-09 13:38 UTC, lfrancke commented on update_feature_tracker_db.sh
> +#!/bin/bash
Sorry, accidentally published my draft comment. I think this has been fixed already.

2024-01-09 13:38 UTC, lfrancke commented on update_feature_tracker_db.sh
> +#!/bin/bash
Oh no, it has not...I think. Please check :)

2024-01-09 13:47 UTC, razvan commented on update_feature_tracker_db.sh
> +#!/bin/bash
Done in https://github.com/stackabletech/docker-images/pull/528/commits/b0f6ab058c69b6c2d3ad07b33b34e2b44f0f1ebe

2024-01-09 13:49 UTC, lfrancke commented
We need to wait for Github to not be broken again...

2024-01-09 16:34 UTC, lfrancke approved these changes

2024-01-09 16:40 UTC, merged