feat(superset): Add patch that fixes saved queries export
stackabletech/docker-images pull request #539
Opened 2024-01-30 16:35 UTC by sbernauer

# Description

*Please add a description here.*

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
- [ ] Changes are OpenShift compatible
- [ ] All added packages (via microdnf or otherwise) have a comment on why they are added
- [ ] Things not downloaded from Red Hat repositories should be mirrored in the Stackable repository and downloaded from there
- [ ] All packages should have (if available) signatures/hashes verified
- [ ] Does your change affect an SBOM? Make sure to update all SBOMs
```

2024-02-02 11:37 UTC, NickLarsenNZ submitted a review, later dismissed
clever

2024-02-02 11:42 UTC, lfrancke requested changes

2024-02-02 11:42 UTC, lfrancke commented on superset/Dockerfile
> +        findutils \
Add a comment what this is needed for please

2024-02-02 14:31 UTC, lfrancke commented on superset/Dockerfile
> +        findutils \
Yes!

2024-02-02 14:32 UTC, lfrancke commented on superset/Dockerfile
> +        # Needed to find all patch files
```suggestion
        # Needed to find all patch files, used in `apply_patches.sh`
```

2024-02-02 14:33 UTC, lfrancke approved these changes
One nit, looks good otherwise

2024-02-05 08:58 UTC, lfrancke approved these changes

2024-02-05 09:56 UTC, merged

2024-02-05 10:16 UTC, lfrancke commented
Just for documentation purposes: Can you briefly say which version of Superset you expect this to be released in?

2024-02-05 10:51 UTC, sbernauer commented
I'm not entirely sure, but I think it will be in the next patch releases of 3.0.x and 3.1.x