Added the opa authorizer extension
stackabletech/docker-images pull request #58
Opened 2022-02-24 09:53 UTC by fhennig

It works on my machine right now, but the extension still might change. Just creating this PR already for later.

2022-03-09 13:21 UTC, fhennig commented
Note: What should the version of the extension be? Should it be the same as the druid version, or should the authorizer have its own versioning?

2022-03-22 09:38 UTC, maltesander requested changes

2022-03-22 09:38 UTC, maltesander commented on druid/Dockerfile
> +    curl https://repo.stackable.tech/repository/packages/druid/druid-opa-authorizer-${PRODUCT}.tar.gz | tar -xzC /stackable/druid/extensions
Tagging the authorizer with the druid version (as long as it is not upstream like the emitter) keeps us from fixing anything. Two suggestions:
1) Hardcode the version to something like druid-opa-authorizer-0.1.0 (then we can make a new docker release of druid with a fixed 0.1.1 version)
2) Use a separate entry in the `conf.py` as with Kafka

We dont know when or if we can deploy this upstream, so for now i prefer the flexibility.

2022-03-22 11:04 UTC, maltesander approved these changes
LGTM.

2022-03-22 11:06 UTC, merged