feat: Build Druid from source
stackabletech/docker-images pull request #684
Opened 2024-05-17 09:29 UTC by labrenbe

# Description

Successfully ran smoke test with some flakiness that seems to be uncorrelated to this PR.

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
- [ ] Changes are OpenShift compatible
- [ ] All added packages (via microdnf or otherwise) have a comment on why they are added
- [ ] Things not downloaded from Red Hat repositories should be mirrored in the Stackable repository and downloaded from there
- [ ] All packages should have (if available) signatures/hashes verified
- [ ] Add an entry to the CHANGELOG.md file
- [ ] Integration tests ran successfully
```

<details>
<summary>TIP: Running integration tests with a new product image</summary>

The image can be built and uploaded to the kind cluster with the following commands:

```shell
bake --product <product> --image-version <stackable-image-version>
kind load docker-image <image-tagged-with-the-major-version> --name=<name-of-your-test-cluster>
```

See the output of `bake` to retrieve the image tag for `<image-tagged-with-the-major-version>`.
</details>

2024-05-17 09:34 UTC, Maleware requested changes
Please also add a entry to the `Changelog.md`. Other than that, great work :)

2024-05-17 09:34 UTC, Maleware commented
Builds succeeded on `arm64`

2024-05-17 11:22 UTC, maltesander commented on druid/Dockerfile
> +ENV LOG4J_FORMAT_MSG_NO_LOOKUPS=true
This should go into the main image.

2024-05-21 06:59 UTC, sbernauer commented on conf.py
> +                "java-devel": "11",
Nit: I think it would be great if we have the attribute `java-devel` right below `java-base`

2024-05-21 11:29 UTC, lfrancke commented
Thanks for this! I looked at it and have nothing to add that hasn't already been said.

2024-05-23 07:31 UTC, Maleware commented on druid/Dockerfile
> +ENV LOG4J_FORMAT_MSG_NO_LOOKUPS=true
Done https://github.com/stackabletech/docker-images/pull/684/commits/f33bc215feafade57b11ff1727a1c6ae3ef2d1f2

2024-05-23 07:38 UTC, sbernauer submitted a review, later dismissed
Thanks!

2024-05-23 07:38 UTC, sbernauer commented on druid/Dockerfile
> +FROM stackable/image/java-base
Nit, feel free to ignore
```suggestion
# hadolint ignore=DL3006
FROM stackable/image/java-base as final
```

2024-05-23 08:37 UTC, maltesander approved these changes
LGTM!

2024-05-23 08:40 UTC, Maleware approved these changes

2024-05-23 08:40 UTC, merged